spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: book-system-backend
  profiles:
    active: dev
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

